#!/usr/bin/env bun

import { parseArgs } from 'node:util';
import {verifyDockerInstalled} from "../src/verifyDockerInstalled.ts";
import { BuildImage } from "../src/BuildImage.ts";
import { getCurrentBranchName } from "../src/git-utils.ts";
import { BunShellExecutor } from "../src/ShellExecutor.ts";
import * as process from "node:process";

const { values, positionals } = parseArgs({
    args: Bun.argv,
    options: {
        'no-cache': {
            type: 'boolean',
            default: false,
        },
        push: {
            type: 'boolean',
            short: 'p',
        },
        verbose: {
            type: 'boolean',
            short: 'v',
            default: false
        },
        quiet: {
            type: 'boolean',
            short: 'q',
            default: false
        }
    },
    strict: true,
    allowPositionals: true,
});

const { verbose, quiet: silent, "no-cache": skipCache, push } = values;

const tagName =  await getCurrentBranchName();
await verifyDockerInstalled();
const imageBuilder = new BuildImage({
    tagName,
    verbose,
    silent,
    skipCache
}, new BunShellExecutor());

try {
    await imageBuilder.lint();
} catch (e) {
    console.error(`Image Builder failed to build image: ${(e as Error).message}`);
    console.error(e)
    process.exit(1);
}

process.exit(0)