name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.18

      - name: Install Bun dependencies
        run: bun install

      - name: Lint project files
        run: bun run lint

      - name: Lint Dockerfile
        run: bun scripts/lint-docker-file

      # Pre-pull the base image for speed
      - name: Pre-pull base image
        run: docker pull nvidia/cuda:12.4.1-base-ubuntu22.04

      # Set IMAGE_TAG by stripping the leading "v" from the tag name.
      - name: Set image tag environment variable
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          echo "Building Docker image with tag: $IMAGE_TAG"
          bun run build-image --tag "$IMAGE_TAG" --push --quiet
